### ISSUE TITLE
如何从后向前取得指定个数的消息?

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#15]
这应该是一个常见的需求, 但是我没找到解决的办法:

比如进入会话后, 加载最新的20条历史消息, `GetMessages`好像只能指定从某个index开始, 向后取得.

**Comment by heavyrain2012** [comment]
你试一下count传负值看看情况

**Comment by wakuflair** [comment]
fromIndex应该怎么传？

**Comment by heavyrain2012** [comment]
fromIndex就是起点的messageUid，count为正数就是这个id之前的消息（旧消息），为负数就是获取这个id之后的消息（新消息）。

**Comment by wakuflair** [comment]
我们试了一下, 问题解决了.
负数的是向前(旧消息), 正数是向后(新消息)
