### ISSUE TITLE
MessageContent的Extra字段总是null

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#16]
https://github.com/wildfirechat/CS-Client-SDK/blob/7746c6181553d7b83317d1126a6f726b6d0be1e0/CsChatClient/Messages/MessageContent.cs#L25

好像没发现为Extra赋值的代码.

**Comment by heavyrain2012** [comment]
这个是留给客户做扩展用的，注意如果要使用，请使用json，以便保留未来的可扩展性

**Comment by wakuflair** [comment]
协议栈不负责这个字段的值处理吗?
现在是移动端在Extra中设置了JSON数据, C#这边取不到.

**Comment by heavyrain2012** [comment]
好的，我再查一下

**Comment by heavyrain2012** [comment]
已修改，另外加了当个群成员禁言功能，请更新IM服务和SDK进行验证

**Comment by wakuflair** [comment]
更新后问题解决.
