### ISSUE TITLE
UploadMedia方法中`string mediaData`该如何设置?

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#20]
https://github.com/wildfirechat/CS-Client-SDK/blob/fe48158aa0582762961c102e445af6c18365cc72/CsChatClient/ChatClient.cs#L1255

该参数是一个字符串类型, 尝试了以下方法:

1. 直接使用本地文件路径
1. 使用`Encoding.ASCII.GetString(File.ReadAllBytes(@"c:\a.png"))`
1. 使用`Encoding.UTF8.GetString(File.ReadAllBytes(@"c:\a.png"))`
1. 使用`JsonConvert.SerializeObject(File.ReadAllBytes(@"c:\a.png"))`
1. 使用`BitConverter.ToString(File.ReadAllBytes(@"c:\a.png"))`

都上传成功了(能返回url), 但是下载的文件都不正确.
应该如何正确设置?

**Comment by heavyrain2012** [comment]
mediaData需要经过base64 encode才可以，已经给您重新发SDK了，请更新SDK，然后参考demo的test函数里的上传示例
