### ISSUE TITLE
SearchMessage缺少fromIndex参数

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#21]
使用SearchMessage中发现该方法缺少类似[GetMessages](https://github.com/wildfirechat/CS-Client-SDK/blob/7d8a2a5d190ef69f8aefb2c3949a5a0beecfee36/CsChatClient/ChatClient.cs#L1096)的`fromIndex`参数, 
导致不能分页查询. 希望能加上`fromIndex`参数.

另外, 能否修改该方法的行为: 当`keyword`为空的时候, 检索全部聊天记录?  
现在在做聊天记录检索时, 需要`GetMessages`和`SearchMessages`轮流使用, 我个人觉得这两个方法可以统一为一个.

**Comment by heavyrain2012** [comment]
SearchMessage现在是最大搜索出来500条消息每次，一般情况下就足够用了，加上分页意义不大，另外就是现在涉及到的端较多，接口改动兼容比较麻烦，建议保持现状吧。

GetMessages是根据会话来读取消息的，SearchMessages是搜索的，意义不太一样，如果合并功能，容易造成误解

**Comment by wakuflair** [comment]
那先这样吧.
