### ISSUE TITLE
创建群发生异常

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#22]
![image](https://user-images.githubusercontent.com/3471718/83219917-338fec00-a1a4-11ea-98c5-ebdfca4dd085.png)

如图, 实际上群已经创建成功, 但是在执行成功回调时发生异常.

**Comment by heavyrain2012** [comment]
已解决，请更新最新代码验证

**Comment by wakuflair** [comment]
更新后问题解决.
