### ISSUE TITLE
如何更新消息的已读/未读状态

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#25]
看到有`UpdateMessage`方法, 但是该方法接收一个content参数,
不太清楚如何只更新status.

**Comment by heavyrain2012** [comment]
会话有clearUnreadStatus接口，用这个清除未读状态

**Comment by wakuflair** [comment]
但是再次启动客户端后, 调用`GetMessage`获取已发送的消息的`Status`仍然是`MessageStatusSent`.

**Comment by heavyrain2012** [comment]
https://docs.wildfirechat.cn/blogs/已送达和已读回执功能使用说明.html

**Comment by wakuflair** [comment]
谢谢, 明白了.
