### ISSUE TITLE
群管理员不能禁言群成员.

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#26]
返回CODE=248(没有权限).

之前某个版本是可以的.

**Comment by heavyrain2012** [comment]
服务器会判断操作者的身份，当不是管理员的时候就会返回248，确认一下当前用户是不是管理员，可以使用移动端登录，看一下身份状态。

一般情况下，在进入到群设置时，需要强制更新一下群信息和群成员信息，以防有信息同步不完成，使用获取群成员的接口refresh传true就可以强制更新

**Comment by wakuflair** [comment]
已确认当前用户是管理员(通过`GetGroupMembers`, 得到Type为`GroupMemberType.Manager`, 并且查看数据库, t_group_member表, 该用户的type为1), 
但是禁言群成员仍然返回248.

**Comment by heavyrain2012** [comment]
被禁言用户不能是群主或群管理员，请确认一下被禁言用户的身份

**Comment by wakuflair** [comment]
> 被禁言用户的身份

是普通群成员.

**Comment by wakuflair** [comment]
更新后问题解决.
