### ISSUE TITLE
全局消息关键字检索

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#28]
还是有关`SearchMessage`的问题, 该方法需要一个`Conversation`参数,
但是我们现在想要实现全局的消息检索(类似微信的"搜聊天记录", 见下图)

这种不需要指定会话的消息检索, 该如何实现?

![image](https://user-images.githubusercontent.com/3471718/83863741-58f99880-a756-11ea-82b5-cb74adf567eb.png)

**Comment by heavyrain2012** [comment]
SearchConversation 使用这个方法，可以搜索出会话及会话中命中的消息条数，展示某个会话内的命中消息时调用SearchMessage。

使用方法可以参考移动端的处理

**Comment by wakuflair** [comment]
参考移动端使用了`SearchConversation`, 当命中一个消息时(`MarchedCount` == 1), 可以通过`MarchedMessage`取得该消息.
但是当命中多个消息时, `MarchedMessage`是一个"UnknownMessageContent", 并且`Conversation`也是null, 想继承查询也没办法.

DEBUG截图:
![image](https://user-images.githubusercontent.com/3471718/84233666-536ccb80-ab25-11ea-8d9f-d1c1c53b1678.png)

**Comment by heavyrain2012** [comment]
当命中多一条时，marchedMessage就是命中的消息，当命中多条时marchedMessage就无意义，如果需要展示展示所有的命中消息，就需要再次调用searchMessage

**Comment by wakuflair** [comment]
> 就需要再次调用searchMessage

再次调用能解释一下吗? 我用同样的参数再次调用`SearchMessage`, 结果会不一样吗?
