### ISSUE TITLE
"获取某类会话信息"`GetMessages`总是返回空

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#29]
https://github.com/wildfirechat/CS-Client-SDK/blob/8c96671d3bde0755a492068a4f17a53857fe052d/CsChatClient/ChatClient.cs#L1115

这个可指定多个`ConversationType`的方法总是返回空结果,
而几乎同样的参数, 调用`GetMessages`指定单一会话是能正常返回消息的.

**Comment by heavyrain2012** [comment]
已经修改
