### ISSUE TITLE
connect()返回值问题

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#3]
DEBUG发现connect()成功了返回的是false, 而失败了返回的是true.

这是特意设计成这样的吗?

**Comment by heavyrain2012** [comment]
connect返回值true/false表面是否是首次登录，如果是用户第一次在当前设备上登录，就会返回true，其它情况返回false。可以忽略掉这个返回值

**Comment by wakuflair** [comment]
好吧. 这个返回值有点反直觉.
使用上我注意一下.
