### ISSUE TITLE
使用野火私有存储(WF-minio)发送大文件, 客户端崩溃

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#30]
我们搭建了野火私有存储[WF-minio](https://github.com/wildfirechat/WF-minio), 小文件发送都正常.
但是较大的文件( > 100M), 使用C# SDK发送会导致客户端崩溃.

**Comment by heavyrain2012** [comment]
协议栈上传的方法是把所有内容读取到内存然后上传，这样就只能发送较小文件，协议栈内限制是100M，超过100M就无法发送了，微信好像也是100M限制。我们修改一下，超过100M返回错误

**Comment by wakuflair** [comment]
通过直接使用minio sdk上传文件解决了.
