### ISSUE TITLE
同一个帐号在一台PC上多次登录问题

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#31]
服务器的设置:

`server.multi_endpoint false`

看文档这样设置的效果为:
> 当开关关闭时，每个平台只能登录一个客户端，不同平台可以同时在线。

但是现在的效果是同一帐号在一台PC上多次登录后, 两个客户端反复断线重连, 没有将之前客户端踢掉.

**Comment by heavyrain2012** [comment]
有个背景是不能多开，同一个电脑上只能打开一个客户端，如果打开两个客户端，由于他们共用同一个clientId，所以服务器就无法正确处理他们的连接

**Comment by heavyrain2012** [comment]
server.multi_endpoint false 
同一个账户，在不同的PC上，获取token时用的是相同的platform，这样才能踢掉

**Comment by wakuflair** [comment]
> 如果打开两个客户端，由于他们共用同一个clientId

不同的user也是共用同一个clientId吗?

**Comment by heavyrain2012** [comment]
是的，这是由于mqtt协议的问题，只能是一个设备上运行一个实例

**Comment by wakuflair** [comment]
明白了.
