### ISSUE TITLE
OnMessageReaded方法接受到的数据不正确

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#33]
发送一条消息给A用户, 当一段时间之后(我们测试是>4分钟), A用户查看该消息.
我方收到的消息已读回执中, `UserId`和`Conversation`中的`Target`不是A的ID, 而是换成了B用户.
(在这期间我方并未给B用户发送过消息)

**Comment by heavyrain2012** [comment]
确认一下问题，是发送在单聊会话中，还是在群组会话中？

**Comment by wakuflair** [comment]
单聊

**Comment by wakuflair** [comment]
更新后问题解决.

**Comment by sjhgithub** [comment]
似乎Single类型的会话,target不同于其它类型,会单独处理,目前不知道该字段的意义
[接收方]接收到的该消息,sender(from)      等于conversation.target;
[发送方]接收到的该消息,sender(from)[不]等于conversation.target
不明白该conversation.target的意义所在,望指教
