### ISSUE TITLE
发送失败的消息如何获取到它的ClientId?

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#34]
用户可能会消息负载大于5K, 导致消息发送失败, 
但是该消息会进入本地的数据库中.

我们想在这种情况下提示用户一个错误信息, 然后立即从本地数据库中删除该消息
(否则加载历史消息后该失败消息仍会显示, 并且永远发送不出去, 而让用户手动删除不太友好).
但是现在发送失败的回调只有一个err的值, 没有ClientId, 没法删除该消息.

有没有比较好的解决办法?

**Comment by heavyrain2012** [comment]
消息有两个id，一个是messageId，这个是存储在本地数据库的id，另外一个messageUid，这个是在IM服务器的id。当消息发送失败时，只有messageId，不存在messageUid。发送消息时发送消息的函数会返回一个message对象，这个消息内就包含有效的messageId值，可以在失败后用这个值来做后续处理

**Comment by wakuflair** [comment]
明白了.
