### ISSUE TITLE
对比移动端sdk缺少一些参数

### ISSUE THREAD

**Issue by aznanr** [wildfirechat/CS-Client-SDK#39]
1. 比如在发送消息中缺少Prepared回调，是否是cpp sdk没有更新呢
2. 发送文件消息对比移动端 文件上传的回调没有调用,也没有上传文件 
@heavyrain2012

**Comment by heavyrain2012** [comment]
1. 我们稍后会加prepared回调。
2. 移动端能发送文件吗？消息能发送成功吗？如果不成功那么错误码是多少？

**Comment by yaobiao131** [comment]
> 

发送文件消息文件移动端收到的是空的文件，并且cpp端upload的回调也没有调用，应该是没有上传文件，如果我先调用uploadMedia上传文件就可以发送成功，但是对比移动端的调用方法就不一致，而且如果先上传文件的话上传进度界面的显示因为还没有messageid就不好控制

**Comment by aznanr** [comment]
> 1. 我们稍后会加prepared回调。
> 2. 移动端能发送文件吗？消息能发送成功吗？如果不成功那么错误码是多少？

好的，麻烦尽快添加一下哇，感觉对比其他端有很多差异，是否可以同步更新一下哇
