### ISSUE TITLE
isLogined无论登录是否成功, 都返回true

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#4]
通过`ChatClient.Instance().isLogined()`取得的返回值, 无论是否登录成功, 都返回true

**Comment by heavyrain2012** [comment]
这个isLogined是说是否调用过connect，当调用过connect后就是ture，没有调用过connect或者调用 connect后再调用disconnect后就是false。
跟连接状态不是一个概念，连接状态跟登录情况和网络 情况都有关系，概念不同

**Comment by wakuflair** [comment]
理解了.
