### ISSUE TITLE
需要一台电脑多开设备

### ISSUE THREAD

**Issue by doralines** [wildfirechat/CS-Client-SDK#42]
我想问一下是以什么标准获取设备号的，我们现在开发的pc需要多开压测功能，但是又不能多开，想看一下你们是通过什么方式判断的。SDK多个连接就会掉线,,,太难搞了。

**Comment by imndx** [comment]
你好，`clientId`是全局的；

由于多开常被用在做黑产或灰产相关业务场景，造成比较恶劣的社会影响，故被要求限制多开。

如果是测试等原因需要多开，可以打包成不同的应用，来实现多开。
