### ISSUE TITLE
频繁报错异常退出

### ISSUE THREAD

**Issue by doralines** [wildfirechat/CS-Client-SDK#43]
[logs.txt](https://github.com/wildfirechat/CS-Client-SDK/files/13576525/logs.txt)
大概在16:16分 16:17分出现的异常
[公钥统计.txt](https://github.com/wildfirechat/CS-Client-SDK/files/13576526/default.txt)

![image](https://github.com/wildfirechat/CS-Client-SDK/assets/150234314/b5f0a37f-4fd4-4d9b-a01b-395fa144c054)

**Comment by doralines** [comment]
![image](https://github.com/wildfirechat/CS-Client-SDK/assets/150234314/b384bde0-343f-4b5f-8dac-d68fa4b89900)
好像是这块代码..

**Comment by doralines** [comment]
![image](https://github.com/wildfirechat/CS-Client-SDK/assets/150234314/afa7f96f-8dbc-4297-83a2-4bd24c9e89fc)
是不是这里，这个比较急,,现在因为这个原因  老是会报错退出

**Comment by heavyrain2012** [comment]
> ![image](https://private-user-images.githubusercontent.com/150234314/288290882-b384bde0-343f-4b5f-8dac-d68fa4b89900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTE5NzcsIm5iZiI6MTcwMTkxMTY3NywicGF0aCI6Ii8xNTAyMzQzMTQvMjg4MjkwODgyLWIzODRiZGUwLTM0M2YtNGI1Zi04ZGFjLWQ2OGZhNGI4OTkwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QwMTE0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Nzk3YWNjYWRmMzUwOTAxMTBkNGEyMDRiYmYwOWI5YjQzOGU0NmZkY2VmOTBhMzQ1ZDdiMjdlOTVhYjc3YTZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XHw_3rp2T44dhps2V1UbpxsOhy19E0ErmayWpheolN4) 好像是这块代码..

对，看上面的崩溃栈应该就是崩溃在这里。因为协议栈用的都是utf8，c#上层用的都是unicode，这里是把utf8转成unicode。请确认消息发送的字符串格式，是不是server api发送的格式有问题。崩溃这里代码都是开源的，你们可以看见相关的源码，可以调一下

**Comment by doralines** [comment]
> e

我们现在有两端发送消息，PC端我们都没用sdk发送消息，我们只有server api发送消息 和 flutter sdk发送消息，这里我们应该如何排查呢？

**Comment by doralines** [comment]
#include <iostream>
#include <fstream>

std::wstring Utf82Unicode(const std::string& utf8string)
{
    int widesize = ::MultiByteToWideChar(CP_UTF8, 0, utf8string.c_str(), -1, NULL, 0);
    if (widesize == ERROR_NO_UNICODE_TRANSLATION)
    {
        std::ofstream errorFile("error_log.txt", std::ios::app);
        if (errorFile.is_open())
        {
            errorFile << "Invalid UTF-8 sequence. Input string: " << utf8string << std::endl;
            errorFile.close();
        }
        throw std::exception("Invalid UTF-8 sequence.");
    }
    if (widesize == 0)
    {
        std::ofstream errorFile("error_log.txt", std::ios::app);
        if (errorFile.is_open())
        {
            errorFile << "Error in conversion. Input string: " << utf8string << std::endl;
            errorFile.close();
        }
        throw std::exception("Error in conversion.");
    }

    std::vector<wchar_t> resultstring(widesize);
    int convresult = ::MultiByteToWideChar(CP_UTF8, 0, utf8string.c_str(), -1, &resultstring[0], widesize);
    if (convresult != widesize)
    {
        std::ofstream errorFile("error_log.txt", std::ios::app);
        if (errorFile.is_open())
        {
            errorFile << "La falla! Input string: " << utf8string << std::endl;
            errorFile.close();
        }
        throw std::exception("La falla!");
    }

    return std::wstring(&resultstring[0]);
}


这个函数里面我们加了日志，你们看看对吗 C++我们也不太懂

**Comment by heavyrain2012** [comment]
> > e
> 
> 我们现在有两端发送消息，PC端我们都没用sdk发送消息，我们只有server api发送消息 和 flutter sdk发送消息，这里我们应该如何排查呢？

你们可以先想办法缩小范围，比如判断出是哪一端发的消息，发的消息内容是什么

**Comment by heavyrain2012** [comment]
> #include #include
> 
> std::wstring Utf82Unicode(const std::string& utf8string) { int widesize = ::MultiByteToWideChar(CP_UTF8, 0, utf8string.c_str(), -1, NULL, 0); if (widesize == ERROR_NO_UNICODE_TRANSLATION) { std::ofstream errorFile("error_log.txt", std::ios::app); if (errorFile.is_open()) { errorFile << "Invalid UTF-8 sequence. Input string: " << utf8string << std::endl; errorFile.close(); } throw std::exception("Invalid UTF-8 sequence."); } if (widesize == 0) { std::ofstream errorFile("error_log.txt", std::ios::app); if (errorFile.is_open()) { errorFile << "Error in conversion. Input string: " << utf8string << std::endl; errorFile.close(); } throw std::exception("Error in conversion."); }
> 
> ```
> std::vector<wchar_t> resultstring(widesize);
> int convresult = ::MultiByteToWideChar(CP_UTF8, 0, utf8string.c_str(), -1, &resultstring[0], widesize);
> if (convresult != widesize)
> {
>     std::ofstream errorFile("error_log.txt", std::ios::app);
>     if (errorFile.is_open())
>     {
>         errorFile << "La falla! Input string: " << utf8string << std::endl;
>         errorFile.close();
>     }
>     throw std::exception("La falla!");
> }
> 
> return std::wstring(&resultstring[0]);
> ```
> 
> }
> 
> 这个函数里面我们加了日志，你们看看对吗 C++我们也不太懂

可以，如果不行就再调调
