### ISSUE TITLE
如何将某一个群成员设置禁言?

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#6]
只看到设置某个群整体禁言, 但是如何实现只禁言群中的一个成员?

**Comment by heavyrain2012** [comment]
目前SDK和IM服务还不支持这个功能，未来会加入到专业版中

**Comment by wakuflair** [comment]
更新后可以通过`MuteGroupMember`设置/解除群成员禁言了.
但是发现缺少几个功能:
1. 设置/解除禁言的群通知消息
1. 获取群中被禁言成员的列表

**Comment by heavyrain2012** [comment]
群通知已经加了，群成员禁言列表是群成员的状态只，这个值0为普通成员，1为管理员，2为群主，3为禁言

**Comment by wakuflair** [comment]
更新后解决了.
