### ISSUE TITLE
如何取得某用户加入的所有群?

### ISSUE THREAD

**Issue by wakuflair** [wildfirechat/CS-Client-SDK#7]
现在想在通讯录中显示某用户加入的所有的群, 如何实现?

**Comment by heavyrain2012** [comment]
server api有接口可以获取用户的所有群。但一般不建议这么做，因为建群的成本很低，用户可能很快就创建或者加入几百个各种各样的群，全部展现给用户意义不大，建议可以像微信那样，重要的群用户收藏就可以了

**Comment by wakuflair** [comment]
使用SERVER API解决了,谢谢.
